[package]
name = "aea-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
near-sdk = "5.1.0"
borsh = "1.3.1" # Use the version compatible with NEAR SDK 5.1.0
near-contract-standards = "5.1.0"
hex = "0.4.2"
anyhow = "1.0"
neo4rs = "0.8.0"

[dependencies.serde_with]
version = "1.4.0"